### ISSUE TITLE
S3 region input parameter not used by Minio library

### ISSUE THREAD

**Issue by ccacciari** [irods/irods_capability_automated_ingest#127]
**What we want**
Synchronizing a AWS S3 bucket from region eu-west with an iRODS collection.
OS: Centos7, Python: 3.6.8, iRODS: 4.2.7

**What we did**
```
$ python -m irods_capability_automated_ingest.irods_sync start --s3_insecure_connection --synchronous --progress --s3_keypair aws-s3-keypair --s3_region_name eu-west-1 --log_filename test.log --log_level DEBUG /bucket_name /tempZone/home/rods/target
 [Elapsed Time: 0:00:01] |####################################################################################################################################################| (Time:  0:00:01) count:      1 tasks: ------ failures:      1 retries: ------
(rodssync) 
13:29 myhost:/home/irods
```
  
**What we expected**
Successful synchronization: file copied to iRODS target collection.
  
**What we got**  
We got an error "Access denied", with the following error stack:
```
Feb 27 13:29:18 start.sh: [2020-02-27 13:29:18,360: ERROR/ForkPoolWorker-1] Task irods_capability_automated_ingest.sync_task.sync_path[c5f2b14e-595c-11ea-abc0-fa163e036f40] raised unexpected: AccessDenied()
Feb 27 13:29:18 start.sh: Traceback (most recent call last):
Feb 27 13:29:18 start.sh: File "/home/irods/rodssync/lib64/python3.6/site-packages/celery/app/trace.py", line 382, in trace_task
Feb 27 13:29:18 start.sh: R = retval = fun(*args, **kwargs)
Feb 27 13:29:18 start.sh: File "/home/irods/rodssync/lib64/python3.6/site-packages/celery/app/trace.py", line 641, in __protected_call__
Feb 27 13:29:18 start.sh: return self.run(*args, **kwargs)
Feb 27 13:29:18 start.sh: File "/home/irods/rodssync/lib64/python3.6/site-packages/irods_capability_automated_ingest/sync_task.py", line 375, in sync_path
Feb 27 13:29:18 start.sh: raise self.retry(max_retries=max_retries, exc=err, countdown=retry_countdown)
Feb 27 13:29:18 start.sh: File "/home/irods/rodssync/lib64/python3.6/site-packages/celery/app/task.py", line 667, in retry 
Feb 27 13:29:18 start.sh: raise_with_context(exc)
Feb 27 13:29:18 start.sh: File "/home/irods/rodssync/lib64/python3.6/site-packages/irods_capability_automated_ingest/sync_task.py", line 319, in sync_path
Feb 27 13:29:18 start.sh: for obj in itr:
Feb 27 13:29:18 start.sh: File "/home/irods/rodssync/lib64/python3.6/site-packages/minio/api.py", line 1041, in list_objects_v2
Feb 27 13:29:18 start.sh: query=query)
Feb 27 13:29:18 start.sh: File "/home/irods/rodssync/lib64/python3.6/site-packages/minio/api.py", line 1922, in _url_open
Feb 27 13:29:18 start.sh: region = self._get_bucket_region(bucket_name)
Feb 27 13:29:18 start.sh: File "/home/irods/rodssync/lib64/python3.6/site-packages/minio/api.py", line 1852, in _get_bucket_region
Feb 27 13:29:18 start.sh: region = self._get_bucket_location(bucket_name)
Feb 27 13:29:18 start.sh: File "/home/irods/rodssync/lib64/python3.6/site-packages/minio/api.py", line 1894, in _get_bucket_location
Feb 27 13:29:18 start.sh: raise ResponseError(response, method, bucket_name).get_exception()
Feb 27 13:29:18 start.sh: minio.error.AccessDenied
Feb 27 13:29:18 start.sh: [2020-02-27 13:29:18,364: ERROR/MainProcess] Task handler raised error: <MaybeEncodingError: Error sending result: ''(1, <ExceptionInfo: AccessDenied()>, None)''. Reason: ''PicklingError("Can\'t pickle <class \'minio.error.AccessDenied\'>: it\'s not the same object as minio.error.AccessDenied",)''.>
Feb 27 13:29:18 start.sh: Traceback (most recent call last):
Feb 27 13:29:18 start.sh: File "/home/irods/rodssync/lib64/python3.6/site-packages/billiard/pool.py", line 362, in workloop
Feb 27 13:29:18 start.sh: put((READY, (job, i, result, inqW_fd)))
Feb 27 13:29:18 start.sh: File "/home/irods/rodssync/lib64/python3.6/site-packages/billiard/queues.py", line 366, in put
Feb 27 13:29:18 start.sh: self.send_payload(ForkingPickler.dumps(obj))
Feb 27 13:29:18 start.sh: File "/home/irods/rodssync/lib64/python3.6/site-packages/billiard/reduction.py", line 56, in dumps 
Feb 27 13:29:18 start.sh: cls(buf, protocol).dump(obj)
Feb 27 13:29:18 start.sh: billiard.pool.MaybeEncodingError: Error sending result: ''(1, <ExceptionInfo: AccessDenied()>, None)''. Reason: ''PicklingError("Can\'t pickle <class \'minio.error.AccessDenied\'>: it\'s not the same object as minio.error.AccessDenied",)''.
```
  
**Possible solution**  
Add "s3_region_name" parameter to Minio client:
```
  client = Minio(
                     endpoint_domain,
                     access_key=s3_access_key,
                     secret_key=s3_secret_key,
                     secure=s3_secure_connection,
                     http_client=httpClient)
```

**Comment by trel** [comment]
Ah, good find.   If you have a pull request, it would be most welcome.  We don't have tests around the S3 behavior yet.

**Comment by ccacciari** [comment]
Created pull request:
https://github.com/irods/irods_capability_automated_ingest/pull/128
