### ISSUE TITLE
Incomplete SSL shutdown?

### ISSUE THREAD

**Issue by holtgrewe** [irods/irods_capability_automated_ingest#136]
I'm seeing the following when following through the examples... on the machine doing the ingestion

```
(rodssync) -bash-4.2$ python -m irods_capability_automated_ingest.irods_sync start ./src_dir /omicsTestingZone/home/rods/reg_coll --synchronous --progress
 [Elapsed Time: 0:00:05] |######################################################################################################| (Time:  0:00:05) count:      8 tasks: ------ failures: ------ retries: ------
Unable to send message. Connection to remote host may have closed. Releasing connection from pool.
Exception ignored in: <bound method Connection.__del__ of <irods.connection.Connection object at 0x7fda79edaa20>>
Traceback (most recent call last):
  File "/var/lib/irods/rodssync/lib/python3.6/site-packages/irods/connection.py", line 73, in __del__
  File "/var/lib/irods/rodssync/lib/python3.6/site-packages/irods/connection.py", line 265, in disconnect
  File "/var/lib/irods/rodssync/lib/python3.6/site-packages/irods/connection.py", line 88, in send
irods.exception.NetworkException: Unable to send message
```

and in the `rodsLogs`

```
Nov 19 23:24:49 pid:37979 remote addresses: 172.16.35.168 ERROR: [-]    /irods_git_repo/server/core/src/rodsAgent.cpp:536:int runIrodsAgentFactory(sockaddr_un) :  status [SSL_SHUTDOWN_ERROR]  errno [] -- message [failed to call 'agent stop']
        [-]     /irods_git_repo/lib/core/src/sockComm.cpp:163:irods::error sockAgentStop(irods::network_object_ptr) :  status [SSL_SHUTDOWN_ERROR]  errno [] -- message [failed to call 'agent stop']
                [-]     /irods_git_repo/plugins/network/ssl/libssl.cpp:942:irods::error ssl_agent_stop(irods::plugin_context &) :  status [SSL_SHUTDOWN_ERROR]  errno [] -- message [error completing shutdown of SSL connection]

Nov 19 23:24:49 pid:34929  ERROR: Agent process [37979] exited with status [64]
```

**Comment by trel** [comment]
Thanks for the report...   we've seen this as well - but have not yet tracked it down.

**Comment by holtgrewe** [comment]
This looks like something happens during garbage cleanup at the end of the program. We got rid of similar problems with the irods python client library by religiously using the connection with `with` context managers...
