### ISSUE TITLE
Sync breaks on '&' in filename

### ISSUE THREAD

**Issue by alanking** [irods/irods_capability_automated_ingest#68]
Need to detect and ignore/escape '&' characters in filenames.
```
$ ls /tmp/s3mockup/93201
mo&relyish
```
Running ingest results in an error:
```
[2018-09-24 14:00:22,750: ERROR/ForkPoolWorker-1] Task irods_capability_automated_ingest.sync_task.sync_files[b4e3a4a4-c023-11e8-9ca5-d4ae528c6f7c] raised unexpected: CAT_UNKNOWN_COLLECTION("collection '/tempZone/home/rods/fs_1400/93201/mo/tempZone/home/rods/fs_1400/93201' is unknown",)
Traceback (most recent call last):
  File "/home/alanking/ingest_venv/lib/python3.4/site-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/alanking/ingest_venv/lib/python3.4/site-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/alanking/irods_capability_automated_ingest/irods_capability_automated_ingest/sync_task.py", line 388, in sync_files
    sync_entry(self, meta, "file", sync_irods.sync_data_from_file, sync_irods.sync_metadata_from_file)
  File "/home/alanking/irods_capability_automated_ingest/irods_capability_automated_ingest/sync_task.py", line 477, in sync_entry
    raise self.retry(max_retries=max_retries, exc=err, countdown=retry_countdown)
  File "/home/alanking/ingest_venv/lib/python3.4/site-packages/celery/app/task.py", line 667, in retry
    raise_with_context(exc)
  File "/home/alanking/irods_capability_automated_ingest/irods_capability_automated_ingest/sync_task.py", line 469, in sync_entry
    datafunc(meta2, logger, True)
  File "/home/alanking/irods_capability_automated_ingest/irods_capability_automated_ingest/sync_irods.py", line 376, in sync_data_from_file
    call(hdlr_mod, "on_data_obj_create", register_file, logger, hdlr_mod, logger, session, meta, **options)
  File "/home/alanking/irods_capability_automated_ingest/irods_capability_automated_ingest/sync_utils.py", line 147, in call
    getattr(hdlr_mod, hdlr)(func, *args, **options)
  File "/home/alanking/irods_capability_automated_ingest/irods_capability_automated_ingest/core.py", line 7, in on_data_obj_create
    func(*args, **options)
  File "/home/alanking/irods_capability_automated_ingest/irods_capability_automated_ingest/sync_irods.py", line 98, in register_file
    session.data_objects.register(phypath_to_register_in_catalog, dest_dataobj_logical_fullpath, **options)
  File "/home/alanking/ingest_venv/lib/python3.4/site-packages/irods/manager/data_object_manager.py", line 339, in register
    response = conn.recv()
  File "/home/alanking/ingest_venv/lib/python3.4/site-packages/irods/connection.py", line 92, in recv
    raise get_exception_by_code(msg.int_info, err_msg)
irods.exception.CAT_UNKNOWN_COLLECTION: collection '/tempZone/home/rods/fs_1400/93201/mo/tempZone/home/rods/fs_1400/93201' is unknown
```
The data object is not created because constructing the logical path fails due to the '&'.

**Comment by alanking** [comment]
This is actually an issue in the PRC. Created irods/python-irodsclient#137
