### ISSUE TITLE
Redis 3.0.0 not working

### ISSUE THREAD

**Issue by alanking** [irods/irods_capability_automated_ingest#76]
We should pin down the Redis version number to redis==2.10.6 to avoid the following error
```
[2018-11-15 17:47:14,406: CRITICAL/MainProcess] Unrecoverable error: AttributeError("'float' object has no attribute 'items'",)
Traceback (most recent call last):
  File "/var/lib/irods/rodssync/lib/python3.5/site-packages/celery/worker/worker.py", line 205, in start
    self.blueprint.start(self)
  File "/var/lib/irods/rodssync/lib/python3.5/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/var/lib/irods/rodssync/lib/python3.5/site-packages/celery/bootsteps.py", line 369, in start
    return self.obj.start()
  File "/var/lib/irods/rodssync/lib/python3.5/site-packages/celery/worker/consumer/consumer.py", line 317, in start
    blueprint.start(self)
  File "/var/lib/irods/rodssync/lib/python3.5/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/var/lib/irods/rodssync/lib/python3.5/site-packages/celery/worker/consumer/consumer.py", line 593, in start
    c.loop(*c.loop_args())
  File "/var/lib/irods/rodssync/lib/python3.5/site-packages/celery/worker/loops.py", line 91, in asynloop
    next(loop)
  File "/var/lib/irods/rodssync/lib/python3.5/site-packages/kombu/asynchronous/hub.py", line 354, in create_loop
    cb(*cbargs)
  File "/var/lib/irods/rodssync/lib/python3.5/site-packages/kombu/transport/redis.py", line 1040, in on_readable
    self.cycle.on_readable(fileno)
  File "/var/lib/irods/rodssync/lib/python3.5/site-packages/kombu/transport/redis.py", line 337, in on_readable
    chan.handlers[type]()
  File "/var/lib/irods/rodssync/lib/python3.5/site-packages/kombu/transport/redis.py", line 724, in _brpop_read
    self.connection._deliver(loads(bytes_to_str(item)), dest)
  File "/var/lib/irods/rodssync/lib/python3.5/site-packages/kombu/transport/virtual/base.py", line 983, in _deliver
    callback(message)
  File "/var/lib/irods/rodssync/lib/python3.5/site-packages/kombu/transport/virtual/base.py", line 632, in _callback
    self.qos.append(message, message.delivery_tag)
  File "/var/lib/irods/rodssync/lib/python3.5/site-packages/kombu/transport/redis.py", line 149, in append
    pipe.zadd(self.unacked_index_key, time(), delivery_tag) \
  File "/var/lib/irods/rodssync/lib/python3.5/site-packages/redis/client.py", line 2263, in zadd
    for pair in iteritems(mapping):
  File "/var/lib/irods/rodssync/lib/python3.5/site-packages/redis/_compat.py", line 123, in iteritems
    return iter(x.items())
AttributeError: 'float' object has no attribute 'items'
```

**Comment by alanking** [comment]
celery/celery#5175 offers the "pin down Redis version" solution as well. One comment claims this has been fixed in kombu and celery's master branch.
