### ISSUE TITLE
watch subcommand should cleanly handle KeyboardInterrupt

### ISSUE THREAD

**Issue by trel** [irods/irods_capability_automated_ingest#93]

**Comment by alanking** [comment]
Is the idea here to catch the `KeyboardInterrupt` exception and exit with a code of 0?

**Comment by trel** [comment]
I believe so, yes.   Just 'stop' watching and let go cleanly.

Please paste here what happens today so we can confirm.

**Comment by alanking** [comment]
```
$ python3 -m irods_capability_automated_ingest.irods_sync watch a5273a18-81a0-11ef-9921-0242ac190006
 [Elapsed Time: 0:00:03] |####################################################################################################################################                                  | (ETA:   0:00:00) count:      5 tasks:      1 failures: ------ retries: ------^C
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.11/site-packages/irods_capability_automated_ingest/irods_sync.py", line 424, in <module>
    main()
  File "/usr/local/lib/python3.11/site-packages/irods_capability_automated_ingest/irods_sync.py", line 420, in main
    sys.exit(args.func(args))
             ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/irods_capability_automated_ingest/irods_sync.py", line 210, in handle_watch
    return sync_actions.monitor_job(args.job_name, True, get_config(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/irods_capability_automated_ingest/sync_actions.py", line 112, in monitor_job
    time.sleep(1)
KeyboardInterrupt

$ echo $?
130
```

**Comment by trel** [comment]
Right, okay - yes, please make it cleanly return a 0.   No barfing on the customer.
